--[[1009

]]
local t = {
'o_cardtype',
{
	{
		['name']=0x10090001,
		['showname']='英雄',
		['界面控件']='v_card_hero',
		['职业边框']='英雄边框',
	},
	{
		['name']=0x10090002,
		['showname']='英雄卡',
		['界面控件']='v_card_herocard',
		['职业边框']='英雄卡边框',
	},
	{
		['name']=0x10090003,
		['showname']='英雄技能',
		['界面控件']='v_card_herospell',
		['职业边框']='英雄技能边框',
	},
	{
		['name']=0x10090004,
		['showname']='随从卡',
		['界面控件']='v_card_minion',
		['职业边框']='随从卡边框',
	},
	{
		['name']=0x10090005,
		['showname']='法术卡',
		['界面控件']='v_card_spell',
		['职业边框']='法术卡边框',
	},
	{
		['name']=0x10090006,
		['showname']='武器卡',
		['界面控件']='v_card_weapon',
		['职业边框']='武器卡边框',
	},
}}
return t