local t ={
	[1] = {
		[1] = {
			name = '卡牌',
			[1] = 'o_cardtype',
			[2] = 'o_category',
			[3] = 'o_profession',
			[4] = 'o_race',
			[5] = 'o_randomiter',
			[6] = 'o_rank',
			[7] = 'o_skill',
		},
		[2] = {
			name = '卡牌汇总',
			[1] = 'o_card',
			[2] = 'o_card_brm',
			[3] = 'o_card_expert',
			[4] = 'o_card_gvg',
			[5] = 'o_card_honours',
			[6] = 'o_card_kar',
			[7] = 'o_card_loe',
			[8] = 'o_card_naxx',
			[9] = 'o_card_tgt',
			[10] = 'o_card_wog',
		},
		[3] = {
			name = '系统',
			[1] = 'o_animation',
			[2] = 'o_event',
			[3] = 'o_font',
			[4] = 'o_fontstyle',
			[5] = 'o_image',
			[6] = 'o_typedef',
		},
	},
	[2] = {
		[1] = {
			name = '卡牌UI',
			[1] = 'v_battle_hero',
			[2] = 'v_battle_herospell',
			[3] = 'v_battle_minion',
			[4] = 'v_battle_weapon',
			[5] = 'v_card_hero',
			[6] = 'v_card_herocard',
			[7] = 'v_card_herospell',
			[8] = 'v_card_manager',
			[9] = 'v_card_minion',
			[10] = 'v_card_spell',
			[11] = 'v_card_weapon',
		},
		[2] = {
			name = '战场UI',
			[1] = 'v_battle_1v1',
			[2] = 'v_battle_playqueue_enemy',
			[3] = 'v_battle_playqueue_self',
			[4] = 'v_battlehero_enemy',
			[5] = 'v_battlehero_friend',
			[6] = 'v_battlehero_self',
			[7] = 'v_battlemana_enemy',
			[8] = 'v_battlemana_self',
			[9] = 'v_battleminion_enemy',
			[10] = 'v_battleminion_self',
			[11] = 'v_choose',
			[12] = 'v_handcards_enemy',
			[13] = 'v_handcards_friend',
			[14] = 'v_handcards_self',
			[15] = 'v_history',
			[16] = 'v_pop_pointline',
			[17] = 'v_record',
		},
		[3] = {
			name = '测试UI',
		},
	},
	[3] = {
		[1] = {
			name = 'excel功能',
			[1] = 'p_cls_data_excelfixfunc',
			[2] = 'p_cls_data_excelreader',
		},
	},
	[4] = {
	},
	[5] = {
	},

}
return t